name: refresh ptc cache

on:
  schedule:
    - cron: '*/1 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 签出仓库
        uses: actions/checkout@v3
      
      - name: 运行中...
        run: |
          chmod +x *
          ./refresh-ptc.sh
